version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: gestor_dicom_db
    environment:
      POSTGRES_USER: admin_dicom
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: dicom_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend_dicom:
    build: .
    container_name: gestor_dicom_api
    ports:
      - "8866:8866"
    environment:
      - SECURE_COOKIE=false
      - DATABASE_URL=postgresql://admin_dicom:superpassword123@db_postgres/dicom_database
    volumes:
      - ./archivos_recibidos:/app/archivos_recibidos
    depends_on:
      - db_postgres
    restart: always

volumes:
  postgres_data:
