version: '3.8'

services:
  backend_dicom:
    build: .
    container_name: gestor_dicom_api
    ports:
      - "8000:8000"
    volumes:
      - ./archivos_recibidos:/app/archivos_recibidos
    restart: unless-stopped
