version: '3.8'

services:
  backend_dicom:
    build: .
    container_name: gestor_dicom_api
    ports:
      - "8866:8866"
    environment:
      - SECURE_COOKIE=false
    volumes:
      - ./archivos_recibidos:/app/archivos_recibidos
    restart: always
